In [6]:
import pandas as pd
from sklearn.decomposition import PCA

pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', None)
pd.set_option('display.precision', 3)

In [7]:
data = pd.read_csv('sample_data/clinic_sympt.csv', sep=',', na_values=".")
data_clean = data.drop([
    'participant_id',
    'id',
    'recruit_date',
    'postal_code',
    'province',
    'family_country',
    'row_school',
    'bus',
    'sports_type',
    'm2',
    'rooms',
    'floor_level',
    'persons_home',
    'survey_type',
    'housemember_symptoms___1',
    'housemember_symptoms___2',
    'housemember_symptoms___3',
    'housemember_symptoms___4',
    'housemember_symptoms___5',
    'school_symptoms_member___1',
    'school_symptoms_member___2',
    'school_symptoms_member___4',
    'school_symptoms_member___5',
    'simptomatology_date',
    'cxr_date',
    'thoracic_ct_date',
    'survey_end_date',
    'date_fever',
    'end_fever',
    'pcr_date',
    'antigenic_date',
    'final_diagnosis_text', #it can be referenced by final_diagnosis_code
    'comments'
    ], axis=1)

In [3]:
data_clean.to_csv("data/cleaned_data.csv", index=False)

In [4]:
two_categorical_cols = ['sex', 'sports', 'smokers_home', 'inclusion_criteria', 'fever', 'ausc_resp', 'wheezing',
                        'crackles', 'cxr2', 'ct2']

data_clean[two_categorical_cols] = data_clean[two_categorical_cols] - 1
data_clean['final_diagnosis_code'] = data_clean['final_diagnosis_code'].apply(lambda x: 1 if x <= 2 else 0)

def rmissingvaluecol(dff, threshold):
    l = []
    l = list(dff.drop(dff.loc[:, list((100 * (dff.isnull().sum() / len(dff.index)) >= threshold))].columns,
                      1).columns.values)
    return l


l = rmissingvaluecol(data_clean, 90)
data_clean = data_clean[l]

In [5]:
data_clean.to_csv("data/cleaned_data_eloy.csv", index=False)

In [8]:
two_categorical_cols = ['sex', 'sports', 'smokers_home', 'inclusion_criteria', 'fever', 'ausc_resp', 'wheezing',
                        'crackles', 'cxr2', 'ct2']

In [10]:
data_clean[two_categorical_cols]

      sex  sports  smokers_home  inclusion_criteria  fever  ausc_resp  wheezing  crackles  cxr2  ct2
0     1.0     2.0           2.0                 1.0    1.0        2.0       1.0       2.0   NaN  NaN
1     2.0     2.0           2.0                 1.0    1.0        2.0       2.0       1.0   NaN  NaN
2     1.0     2.0           2.0                 1.0    1.0        1.0       NaN       NaN   NaN  NaN
3     2.0     2.0           2.0                 1.0    2.0        2.0       1.0       2.0   NaN  NaN
4     2.0     2.0           2.0                 1.0    1.0        1.0       NaN       NaN   NaN  NaN
...   ...     ...           ...                 ...    ...        ...       ...       ...   ...  ...
1676  1.0     NaN           NaN                 1.0    1.0        1.0       NaN       NaN   NaN  NaN
1677  2.0     NaN           NaN                 1.0    1.0        1.0       NaN       NaN   NaN  NaN
1678  1.0     2.0           2.0                 1.0    1.0        1.0       NaN       NaN   NaN  NaN
1679  1.0     2.0           2.0                 1.0    2.0        1.0       NaN       NaN   NaN  NaN
1680  2.0     1.0           1.0                 1.0    1.0        1.0       NaN       NaN   NaN  NaN

[1681 rows x 10 columns]

In [12]:
data_clean[two_categorical_cols] - 1

      sex  sports  smokers_home  inclusion_criteria  fever  ausc_resp  wheezing  crackles  cxr2  ct2
0     0.0     1.0           1.0                 0.0    0.0        1.0       0.0       1.0   NaN  NaN
1     1.0     1.0           1.0                 0.0    0.0        1.0       1.0       0.0   NaN  NaN
2     0.0     1.0           1.0                 0.0    0.0        0.0       NaN       NaN   NaN  NaN
3     1.0     1.0           1.0                 0.0    1.0        1.0       0.0       1.0   NaN  NaN
4     1.0     1.0           1.0                 0.0    0.0        0.0       NaN       NaN   NaN  NaN
...   ...     ...           ...                 ...    ...        ...       ...       ...   ...  ...
1676  0.0     NaN           NaN                 0.0    0.0        0.0       NaN       NaN   NaN  NaN
1677  1.0     NaN           NaN                 0.0    0.0        0.0       NaN       NaN   NaN  NaN
1678  0.0     1.0           1.0                 0.0    0.0        0.0       NaN       NaN   NaN  NaN
1679  0.0     1.0           1.0                 0.0    1.0        0.0       NaN       NaN   NaN  NaN
1680  1.0     0.0           0.0                 0.0    0.0        0.0       NaN       NaN   NaN  NaN

[1681 rows x 10 columns]

In [16]:
data_clean.loc[:, list((100 * (data_clean.isnull().sum() / len(data_clean.index)) >= 90))].columns

Index(['crup_first', 'disfonia_first', 'dyspnea_first', 'tachypnea_first',
       'auscult_first', 'wheezing', 'crackles', 'conj_first', 'ocular_first',
       'skin_first', 'rash', 'inflam_periferic', 'inflam_oral', 'lymph_first',
       'hepato_first', 'spleno_first', 'hemorr_first', 'irritability_first',
       'neuro_first', 'confusion', 'seizures', 'nuchal_stiffness', 'hypotonia',
       'peripheral_paralysis', 'shock_first', 'taste_first', 'smell_first',
       'other_simptomatology', 'other_simptomatology_3',
       'other_simptomatology_4', 'other_simptomatology_lliure',
       'sero_type_response', 'sero_method', 'sero_date', 'sero_response',
       'sero_type_response_2', 'cxr2', 'ct2', 'otherviruses_date',
       'vrs_result', 'adeno_result', 'flu_a_result', 'flu_b_result',
       'picu_adm', 'adm_date', 'discharge_date', 'coviral_type',
       'other_viruses_text', 'bacterial_type', 'obesity', 'other', 'flu_date'],
      dtype='object')

In [17]:
data_clean.isnull().sum()

sex                              4
sports                         482
smokers_home                   156
inclusion_criteria            1200
sympt_epi                       17
                              ...
vaccines_binary                 17
comorbidities_complete           0
final_classification_of_th     327
name_initials_of_the_inter     177
final_outcome_complete           0
Length: 164, dtype: int64

In [19]:
len(data_clean.index)

1681

In [21]:
data_clean.isnull().sum() /len(data_clean.index)

sex                           0.002
sports                        0.287
smokers_home                  0.093
inclusion_criteria            0.714
sympt_epi                     0.010
                              ...
vaccines_binary               0.010
comorbidities_complete        0.000
final_classification_of_th    0.195
name_initials_of_the_inter    0.105
final_outcome_complete        0.000
Length: 164, dtype: float64